### ISSUE TITLE
Timer issue

### ISSUE THREAD

**Issue by Ram-smith** [mriscoc/Marlin_Ender3v2#159] opened 2021-12-01 15:23 UTC
Hi the timer is showing an odd time read out with 3 digits in the minutes area.  Please see photo 
![Screenshot_20211201-092325](https://user-images.githubusercontent.com/95066525/144262220-bfa561d1-3d8c-43c1-9ad3-850860b6f239.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mriscoc** [comment] 2021-12-04 00:07
Thanks for your report, please, can you elaborate the steps to reproduce the issue? How long was the real remain time? Are you printing from Octoprint?

**Comment by mriscoc** [comment] 2021-12-12 01:13
Because no more feedback was written, I'm going to close this issue.

**Closed by mriscoc** 2021-12-12 01:13 UTC
